apiVersion: v1
kind: Service
metadata:
  name: demo-app-svc
  namespace: ns-demo-hcp
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5678
    nodePort: 30090
  selector:
    app: demo-app-hcp
