apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-external-secret
  namespace: ns-demo-hcp
spec:
  refreshInterval: 2m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  data:
  - secretKey: SECRET_VALUE
    remoteRef:
      key: hello-world
      property: SECRET_VALUE
