apiVersion: v1
kind: Pod
metadata:
  name: vault-dev
  namespace: hcp-vault
  labels:
    app: vault
spec:
  containers:
  - name: vault
    image: hashicorp/vault:1.16.1
    args:
    - "server"
    - "-dev"
    ports:
    - containerPort: 8200
    env:
    - name: VAULT_DEV_ROOT_TOKEN_ID
      value: "root"
