apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-external-secret
  namespace: ns-demo
spec:
  refreshInterval: 2m
  secretStoreRef:
    name: local-secret-store
    kind: SecretStore
  target:
    name: demo-external-secret
    creationPolicy: Owner
  data:
  - secretKey: SECRET_VALUE
    remoteRef:
      key: demo-secret
      property: SECRET_VALUE
