apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-eso-store-role
  namespace: ns-demo
rules:
- apiGroups: [ "" ]
  resources: [ "secrets" ]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-eso-store-rolebinding
  namespace: ns-demo
subjects:
- kind: ServiceAccount
  name: demo-store
  namespace: ns-demo
roleRef:
  kind: Role
  name: demo-eso-store-role
  apiGroup: rbac.authorization.k8s.io
