apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: local-secret-store
  namespace: ns-demo
spec:
  provider:
    kubernetes:
      remoteNamespace: ns-demo
      auth:
        serviceAccount:
          name: demo-store
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
